version: '3'
services:
  redis:
    image: 'redis:alpine'
  master:
    image: 'aspyatkin/themis-finals-devenv-master:v1.0.0'
    ports:
      - '8000:80'
    env_file:
      - themis-finals-private.env
      - themis-finals-public.env
      - themis-finals-auth.env
  checker:
    # TODO: replace with your own image
    image: 'aspyatkin/themis-finals-devenv-checker:v1.2.0'
    env_file:
      - themis-finals-public.env
      - themis-finals-auth.env
    # To enable reload capabilities, uncomment the following lines
    # tty: true
    # volumes:
    #   - '/path/to/your/checker/src:/src'
    # command: ['python', '-m', 'watchgod', 'server.main']
  service:
    # TODO: replace with your own image
    image: 'aspyatkin/themis-finals-devenv-service:v1.0.0'
