version: '3'
services:
  redis:
    image: 'redis:alpine'
  master:
    image: 'volgactf/volgactf-final-devenv-master:4.0.0'
    # Use for development/debug purposes
    # build: '/path/to/volgactf-final-devenv-master'
    # volumes:
    #   - '/path/to/volgactf-final-devenv-master/src:/dist'
    ports:
      - '8000:80'
    env_file:
      - volgactf-final-private.env
      - volgactf-final-public.env
      - volgactf-final-auth.env
    # environment:
    #   - DEFAULT_TEAM_NAME=Roosters
    #   - DEFAULT_SERVICE_NAME=Jinn The Ripper
    #   - DEFAULT_FLAG_LIFETIME=180
    #   - DEFAULT_ROUND_TIMESPAN=90
    #   - DEFAULT_POLL_TIMESPAN=25
    #   - DEFAULT_POLL_DELAY=10
    #   - LOG_HISTORY=250
    #   - FLAG_HISTORY=25
  checker:
    # TODO: replace with your own image
    image: 'volgactf/volgactf-final-devenv-checker:4.0.0'
    # OR comment out the line above and uncomment
    # the following lines for development/debug purposes:
    # build: '/path/to/your-checker'
    # volumes:
    #   - '/path/to/your-checker/src:/dist/checker'
    # tty: true
    # command: ['python', '-m', 'watchgod', 'server.main']
    env_file:
      - volgactf-final-public.env
      - volgactf-final-auth.env
    # environment:
    #   - LOG_LEVEL=DEBUG  # more verbose logging
    #   - VOLGACTF_FINAL_PING_ENABLED=yes
  service:
    # TODO: replace with your own image
    image: 'volgactf/volgactf-final-devenv-service:2.0.1'
