version: '3'
services:
  redis:
    image: 'redis:alpine'
  master:
    build: './master'
    ports:
      - '8000:80'
    volumes:
      - './master:/code'
    env_file:
      - themis-finals-private.env
      - themis-finals-public.env
      - themis-finals-auth.env
  checker:
    build: './checker'
    volumes:
      - './checker:/code'
    env_file:
      - themis-finals-public.env
      - themis-finals-auth.env
  service:
    build: './service'
    volumes:
      - './service:/code'
