version: '3'
services:
  redis:
    image: 'redis:alpine'
  master:
    build: './master'
    ports:
      - '5001:5000'
    volumes:
      - './master:/code'
    environment:
      - THEMIS_FINALS_CHECKER_HOSTNAME=checker
    env_file:
      - themis-finals-private.env
      - themis-finals-public.env
      - themis-finals-auth.env
  checker:
    build: './checker'
    ports:
      - '5002:5000'
    volumes:
      - './checker:/code'
    environment:
      - HOST=0.0.0.0
      - PORT=5000
    env_file:
      - themis-finals-public.env
      - themis-finals-auth.env
